
project_id = "mkwinxbualpcivkujlfd"

[functions.generate-post]
verify_jwt = false

[functions.test-qwen-key]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.test-gemini-key]
verify_jwt = false

[functions.manage-secrets]
verify_jwt = false
