
project_id = "mkwinxbualpcivkujlfd"

[functions.gemini-image-generate]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[auth]
# Allow users to sign in without email verification
disable_signup = false
enable_signup = true

